package be.codewriter.melodymatrix.view.test

import be.codewriter.melodymatrix.view.VisualizerStage
import be.codewriter.melodymatrix.view.component.ScaledContentPane
import be.codewriter.melodymatrix.view.data.LicenseStatus
import be.codewriter.melodymatrix.view.stage.chart.ChartsStage
import be.codewriter.melodymatrix.view.stage.chord.ChordStage
import be.codewriter.melodymatrix.view.stage.guitar.GuitarStage
import be.codewriter.melodymatrix.view.stage.midi.MidiStage
import be.codewriter.melodymatrix.view.stage.piano.PianoStage
import be.codewriter.melodymatrix.view.video.DummyVideoRecorder
import javafx.event.EventHandler
import javafx.geometry.Insets
import javafx.geometry.Orientation
import javafx.scene.Node
import javafx.scene.layout.VBox
import javafx.stage.WindowEvent
import software.coley.bentofx.Bento
import software.coley.bentofx.dockable.Dockable
import stage.drum.DrumStage
import stage.ledstrip.LedStripStage
import stage.scale.ScaleStage

/**
 * Root UI component for the standalone test application.
 *
 * Assembles a dockable multi-panel layout (using BentoFX) that contains:
 * - A **stage selector** panel for toggling individual visualizer tabs on/off
 * - A **visualizer tab area** where each active [VisualizerStage] is embedded as a scaled tab
 * - A **right column** with MIDI event inspection and license status panels
 *
 * MIDI events are generated by an embedded [MidiSimulator] and forwarded to all currently
 * active visualizer stages.
 *
 * @see TestLauncher
 * @see MidiSimulator
 * @see VisualizerStage
 */
class TestView : VBox() {

    private val stageSelectorWidth = 260.0
    private val visualizerWidth = 1660.0
    private val rightColumnWidth = 430.0
    private val mainSectionTotalWidth = stageSelectorWidth + visualizerWidth + rightColumnWidth
    private val firstDividerPosition = stageSelectorWidth / mainSectionTotalWidth
    private val secondDividerPosition = (stageSelectorWidth + visualizerWidth) / mainSectionTotalWidth
    private val rightColumnDividerPosition = 0.66

    private val midiSimulator = MidiSimulator()
    private val licenseStatus = LicenseStatus()

    private val bento = Bento()
    private val rootContainer = bento.dockBuilding().root("test-root")
    private val stageSelectorLeaf = bento.dockBuilding().leaf("stage-selector-leaf")
    private val visualizerTabs = bento.dockBuilding().leaf("visualizer-tabs")
    private val rightColumnBranch = bento.dockBuilding().branch("right-column-branch")
    private val midiEventsLeaf = bento.dockBuilding().leaf("midi-events-leaf")
    private val licenseLeaf = bento.dockBuilding().leaf("license-leaf")

    private val stageOptions = listOf(
        StageOption("Midi", "tab-midi") { MidiStage() },
        StageOption("Piano", "tab-piano") { PianoStage(licenseStatus, DummyVideoRecorder(), true) },
        StageOption("Chord", "tab-chord") { ChordStage() },
        StageOption("Guitar", "tab-guitar") { GuitarStage() },
        StageOption("Charts", "tab-charts") { ChartsStage() },
        StageOption("Scale", "tab-scale") { ScaleStage() },
        StageOption("Drum", "tab-drum") { DrumStage() },
        StageOption("LED Strip", "tab-led-strip") { LedStripStage() }
    )

    private val optionsById = stageOptions.associateBy { it.id }
    private val activeVisualizers: MutableMap<String, ActiveVisualizer> = linkedMapOf()
    private val stageSelector = TestViewStages(
        stageOptions.map { TestViewStages.Option(it.id, it.label) },
        ::toggleVisualizer
    )

    init {
        spacing = 10.0
        padding = Insets(10.0)

        setupDockLayout()
        bento.registerRoot(rootContainer)

        children.add(rootContainer)
    }

    /**
     * Lays out the BentoFX dock containers and registers all fixed panels.
     */
    private fun setupDockLayout() {
        val stageSelectorDockable = createFixedDockable(
            id = "stage-selector",
            title = "Stages",
            content = stageSelector
        )

        val midiEventsDockable = createFixedDockable(
            id = "midi-events",
            title = "MIDI Events",
            content = TestViewMidiEvents(midiSimulator)
        )

        val licenseDockable = createFixedDockable(
            id = "license-status",
            title = "License",
            content = TestViewLicense(licenseStatus)
        )

        rightColumnBranch.orientation = Orientation.VERTICAL
        rightColumnBranch.setPruneWhenEmpty(false)
        rightColumnBranch.addContainers(midiEventsLeaf, licenseLeaf)
        rightColumnBranch.setDividerPositions(rightColumnDividerPosition)

        visualizerTabs.setPruneWhenEmpty(false)
        rootContainer.addContainers(stageSelectorLeaf, visualizerTabs, rightColumnBranch)
        rootContainer.setPruneWhenEmpty(false)
        // left ~260 / (260 + 1660 + 430) ≈ 0.11, left+center ≈ 0.82
        rootContainer.setDividerPositions(firstDividerPosition, secondDividerPosition)

        stageSelectorLeaf.addDockable(stageSelectorDockable)
        stageSelectorLeaf.selectDockable(stageSelectorDockable)

        midiEventsLeaf.addDockable(midiEventsDockable)
        midiEventsLeaf.selectDockable(midiEventsDockable)

        licenseLeaf.addDockable(licenseDockable)
        licenseLeaf.selectDockable(licenseDockable)

        stageSelectorLeaf.minWidth = 260.0
        stageSelectorLeaf.prefWidth = stageSelectorWidth
        visualizerTabs.minWidth = 300.0
        rightColumnBranch.minWidth = 320.0
        rightColumnBranch.prefWidth = rightColumnWidth
        rootContainer.prefHeight = 800.0
    }

    /**
     * Creates a non-closable, non-draggable [Dockable] wrapping the given content node.
     *
     * @param id      Unique identifier for the dockable
     * @param title   Display title shown in the tab header
     * @param content The JavaFX node to embed
     * @return A configured [Dockable] instance
     */
    private fun createFixedDockable(
        id: String,
        title: String,
        content: Node
    ): Dockable {
        return bento.dockBuilding().dockable(id).apply {
            this.titleProperty().set(title)
            this.nodeProperty().set(content)
            this.isClosable = false
            this.isCanBeDragged = false
            this.isCanBeDroppedToNewWindow = false
        }
    }

    /**
     * Shuts down all active visualizers and the MIDI simulator.
     *
     * Should be called when the application window is closed to release resources cleanly.
     */
    fun shutdown() {
        activeVisualizers.values.toList().forEach { active ->
            disposeVisualizer(active)
        }
        activeVisualizers.clear()
        midiSimulator.stop()
        midiSimulator.scheduler.shutdownNow()
    }

    /**
     * Toggles a visualizer on or off based on the selection state from [TestViewStages].
     *
     * @param id       The [StageOption] identifier
     * @param selected True to open the visualizer, false to close it
     */
    private fun toggleVisualizer(id: String, selected: Boolean) {
        val option = optionsById[id] ?: return
        if (selected) {
            openVisualizer(option)
        } else {
            closeVisualizer(option)
        }
    }

    /**
     * Opens a new visualizer tab for the given [StageOption].
     *
     * Creates the stage, wraps its content in a [ScaledContentPane], registers it with the
     * MIDI simulator, and adds it as a dockable tab in the visualizer leaf.
     *
     * @param option The stage option describing which visualizer to open
     */
    private fun openVisualizer(option: StageOption) {
        if (activeVisualizers.containsKey(option.id)) {
            return
        }

        ensureVisualizerLeafAttached()

        val stage = option.stageSupplier()
        val content = ScaledContentPane.fromStage(stage)
        val closeHandler = stage.onCloseRequest

        val dockable: Dockable = bento.dockBuilding().dockable(option.id).apply {
            titleProperty().set(option.label)
            nodeProperty().set(content)
            isCanBeDroppedToNewWindow = false
            addCloseListener { _, _ ->
                val removed = activeVisualizers.remove(option.id)
                if (removed != null) {
                    disposeVisualizer(removed)
                    stageSelector.setSelected(option.id, false)
                }
            }
        }

        midiSimulator.registerListener(stage)
        visualizerTabs.addDockable(dockable)
        visualizerTabs.selectDockable(dockable)

        activeVisualizers[option.id] = ActiveVisualizer(
            stage = stage,
            dockable = dockable,
            closeHandler = closeHandler
        )
    }

    /**
     * Re-attaches the visualizer leaf to the root container if BentoFX pruned it.
     *
     * This can happen when the last tab in the visualizer area is closed.
     */
    private fun ensureVisualizerLeafAttached() {
        if (visualizerTabs.parentContainer != null) {
            return
        }

        // If Bento pruned the center leaf after the last tab closed, restore it in the middle slot.
        rootContainer.addContainer(1, visualizerTabs)
        rootContainer.setDividerPositions(firstDividerPosition, secondDividerPosition)
    }

    /**
     * Closes the visualizer tab for the given [StageOption] and disposes its resources.
     *
     * @param option The stage option describing which visualizer to close
     */
    private fun closeVisualizer(option: StageOption) {
        val active = activeVisualizers[option.id] ?: return
        val closed = visualizerTabs.closeDockable(active.dockable)
        if (!closed) {
            visualizerTabs.removeDockable(active.dockable)
            activeVisualizers.remove(option.id)
            disposeVisualizer(active)
        }
    }

    /**
     * Unregisters the stage from the MIDI simulator and fires its close-request handler.
     *
     * @param active The active visualizer to dispose
     */
    private fun disposeVisualizer(active: ActiveVisualizer) {
        midiSimulator.removeListener(active.stage)
        active.closeHandler?.handle(WindowEvent(active.stage, WindowEvent.WINDOW_CLOSE_REQUEST))
    }

    /**
     * Describes a visualizer option shown in the stage selector panel.
     *
     * @property label         Human-readable name displayed in the selector
     * @property id            Unique string identifier used as the dockable ID
     * @property stageSupplier Factory lambda that creates a new [VisualizerStage] instance
     */
    private data class StageOption(
        val label: String,
        val id: String,
        val stageSupplier: () -> VisualizerStage
    )

    /**
     * Holds the runtime state of an open visualizer tab.
     *
     * @property stage        The active [VisualizerStage] instance
     * @property dockable     The BentoFX [Dockable] wrapping the visualizer content
     * @property closeHandler The original close-request handler registered on the stage
     */
    private data class ActiveVisualizer(
        val stage: VisualizerStage,
        val dockable: Dockable,
        val closeHandler: EventHandler<WindowEvent>?
    )
}