package be.codewriter.melodymatrix.view.stage.piano.component

enum class PianoProperty {
    ABOVE_KEY_ENABLED,
    ABOVE_KEY_COLOR_START,
    ABOVE_KEY_COLOR_END,
    BACKGROUND_COLOR,
    BACKGROUND_IMAGE,
    BACKGROUND_IMAGE_TRANSPARENCY,
    EXPLOSION_ENABLED,
    EXPLOSION_TYPE,
    EXPLOSION_COLOR,
    EXPLOSION_RANDOM_COLOR,
    EXPLOSION_RADIUS,
    EXPLOSION_NUMBER_OF_PARTICLES,
    EXPLOSION_PARTICLE_SIZE,
    EXPLOSION_TAIL_NUMBER_OF_ARTICLES,
    LOGO_LEFT,
    LOGO_TOP,
    LOGO_TRANSPARENCY,
    LOGO_VISIBLE,
    LOGO_WIDTH,
    PIANO_WHITE_KEY_COLOR,
    PIANO_WHITE_KEY_ACTIVE_COLOR,
    PIANO_WHITE_KEY_NAME_COLOR,
    PIANO_WHITE_KEY_NAME_VISIBLE,
    PIANO_BLACK_KEY_COLOR,
    PIANO_BLACK_KEY_ACTIVE_COLOR
}